#!/bin/bash
git pull
java -jar WoWLogsUpdater.jar
git add Interface/AddOns/WoWLogsDB/WoWLogsDB.lua
git commit -m "Test"
git pull --no-edit
git push
echo "Sleeping for 5 minutes"
sleep 5m

./serverScript
